config/routes.rb
Festivalize::Application.routes.draw do

  root 'festivals#index'

  resources :festivals do
    resources :stages
  end

end

app/models/festival.rb
# == Schema Information
#
# Table name: festivals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  startdate  :datetime
#  created_at :datetime
#  updated_at :datetime
#  enddate    :datetime
#

class Festival < ActiveRecord::Base
  has_many :stages
  accepts_nested_attributes_for :stages, allow_destroy: true, reject_if: :all_blank

  validates :name, :startdate, :enddate, presence: true

end

app/models/stage.rb
# == Schema Information
#
# Table name: stages
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  festivals_id :integer
#

class Stage < ActiveRecord::Base
  belongs_to :festival
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  before_filter :find_festival, only: [:show, :edit, :update]

  def index
    @festivals = Festival.all
  end

  def new
    @festival = Festival.new
    @festival.stages.build
  end

  def create
    @festival = Festival.create(festival_params)
    if @festival.save
      redirect_to @festival, notice: "Festival added"
    else
      flash[:alert] = "Changes failed to save"
      render action: :new
    end
  end

  def edit

  end

  def update
    if @festival.update_attributes(festival_params)
      redirect_to @festival, notice: "Changes saved"
    else
      flash[:alert] = "Changes failed to save"
      render action: :edit
    end
  end

  def show

  end

  private
  def find_festival
    @festival = Festival.find(params[:id])
  end

  def festival_params
    params.require(:festival).permit(:name, :startdate, :enddate, stages_attributes: [:id, :name])
  end

  def flatten_date_array hash
    %w(1 2 3).map { |e| hash["date(#{e}i)"].to_i }
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_filter :find_festival
  def new
    @stage = @festival.stages.build
    @stage.assets.build
  end
  private
  def find_festival
    @festival = Festival.find(params[:festival_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/stage_helper.rb
module StageHelper
end

app/views/festivals/_form.html.erb
<%= form_for @festival do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :startdate, "Start Time" %><br>
  <%= f.datetime_select :startdate %>
</p>

<p>
  <%= f.label :enddate, "End Time" %><br>
  <%= f.datetime_select :enddate %>
</p>

<div id="stages">
<%= f.fields_for :stages do |stage| %>

<%= render 'stage_fields', :f => stage %>
<div class="links">
<%= link_to_add_association 'Add Stage', f, :stages %>
</div>
<% end %>
</div>
<%= f.submit %>
<% end %>

app/views/festivals/_stage_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="links"><%= link_to_remove_association "Remove Stage", f %></div>
</div>

app/views/festivals/edit.html.erb
<h1>Edit <%= @festival.name %></h1>
<%= render "form" %>

app/views/festivals/index.html.erb
<h1>Festivalize</h1>
Plan your festivals here!
<%= link_to "Add New Festival", new_festival_path %>

<% @festivals.each do |f| %>
<br>
<strong><%= link_to f.name, f %></strong> <%= f.startdate.to_s %> to <%= f.enddate.to_s %>
<% end %>

app/views/festivals/new.html.erb
<h1>Add a New Festival</h1>
<%= render "form" %>

app/views/festivals/show.html.erb
<h1><%= @festival.name %></h1>
Start: <%= @festival.startdate %><br>
End: <%= @festival.enddate %><br>

<% if @festival.stages.exists? %>
  <h2>Stages:</h2>
  <ul>
  <% @festival.stages.each do |s| %>
    <li><%= s.name %></li>
  <% end %>
  </ul>
<% end %>

<%= link_to "Edit", edit_festival_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Festivalize</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert <%= name == :notice ? "success" : "error" %>">
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

<%= link_to "Home", root_path %>
<%= yield %>

</body>
</html>

app/views/stages/_form.html.erb
<%= form_for [@festival, @stage] do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<%= f.submit %>
<% end %>

app/views/stages/new.html.erb
<%= render "form" %>